name: studyu_repo_generator
description: A web server to generate/update Gitlab repos
version: 1.4.23
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  args: ^2.3.2
  dotenv: ^4.1.0
  http: ^0.13.5
  path: ^1.8.3
  pretty_json: ^2.0.0
  shelf: ^1.4.0
  studyu_core: ^3.8.2
  supabase: ^0.3.6 # breaking

dev_dependencies:
  lint: ^2.0.1
  shelf_hotreload: ^1.4.0

executables:
  repo_generator:
