name: studyu_repo_generator
description: A web server to generate/update Gitlab repos
version: 1.4.15
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  args: ^2.3.1
  dotenv: ^4.0.1
  http: ^0.13.4
  path: ^1.8.2
  pretty_json: ^2.0.0
  shelf: ^1.3.0
  studyu_core: ^3.7.10
  supabase: ^0.3.4

dev_dependencies:
  lint: 1.8.2
  shelf_hotreload: ^1.1.0

executables:
  repo_generator:
