version: "3.8"

services:
  mail:
    container_name: supabase-mail
    image: inbucket/inbucket:stable
    ports:
      - '2500:2500' # SMTP
      - '9000:9000' # web interface
      - '1100:1100' # POP3
    networks:
      - supabase-dev-net
  meta:
    ports:
      - 5555:8080
    networks:
      - supabase-dev-net
  db:
    volumes:
      - /var/lib/postgresql/data
      - ./dev/data.sql:/docker-entrypoint-initdb.d/data.sql
      - ../database/studyu-schema.sql:/docker-entrypoint-initdb.d/studyu-schema.sql
  storage:
    volumes:
      - /var/lib/storage
networks:
  supabase-dev-net:
    external:
      name: studyu_network