# DEPRECATED in favor of Supabase

version: '3'
services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
  parse:
    image: parseplatform/parse-server
    environment:
      # All env vars: https://github.com/parse-community/parse-server/blob/master/src/Options/Definitions.js
      - PARSE_SERVER_APPLICATION_ID=nof1-local
      - PARSE_SERVER_MASTER_KEY=nof1-local
      - PARSE_SERVER_DATABASE_URI=mongodb://mongodb
      - PARSE_SERVER_HOST=0.0.0.0
      - PARSE_SERVER_ALLOW_HEADERS=X-Parse-Installation-Id
    ports:
      - 1337:1337
    depends_on:
      - mongodb
  parse-dashboard:
    # Using bitnami, because offical repo is not maintained
    image: bitnami/parse-dashboard:2-debian-10
    environment:
      - PARSE_APP_ID=nof1-local
      - PARSE_MASTER_KEY=nof1-local
      - PARSE_HOST=localhost
      - PARSE_MOUNT_PATH=/parse
      - PARSE_PORT_NUMBER=1337
      - PARSE_PROTOCOL=http
      - PARSE_USE_HOSTNAME=no
      - PARSE_DASHBOARD_APP_NAME=StudyU
      - PARSE_DASHBOARD_PASSWORD=nof1
      - PARSE_DASHBOARD_USER=admin
    ports:
      - 4040:4040
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
