name: studyu_workspace
description: The root of the StudyU project
publish_to: none
version: 0.4.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^3.0.1
  lint: ^2.2.0
  melos: ^3.2.0
