version: '3'
name: 'studyu'

services:
  platform-full:
    container_name: platform
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080 # StudyU App
      - 8081:8081 # StudyU Designer
      - 8082:8082 # Supabase Studio (disable if you do not want to self-host Supabase on this machine)
    # - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    env_file:
      - ../flutter_common/lib/envs/.env.selfhost
