name: studyu_core
description: StudyU Models and common functions for app and designer
version: 3.7.15
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  csv: ^5.0.1
  fhir: ^0.4.7 # 0.6.0
  json_annotation: ^4.6.0
  quiver: ^3.1.0
  supabase: ^0.3.6
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lint: ^1.10.0
  test: ^1.21.4
