name: studyu_core
version: 4.0.0
description: StudyU models and common functions for app and designer
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0 # flutter_test
  csv: ^5.0.1
  fhir: ^0.4.7
  json_annotation: ^4.8.0
  quiver: ^3.2.1
  supabase: ^1.6.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lint: ^2.0.1
  test: ^1.23.1
