name: studyu_core
version: 4.3.0-dev.7
description: This package contains StudyU models and common functions for the app and designer packages
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  collection: ^1.17.1 # flutter_test sdk
  csv: ^5.0.2
  json_annotation: ^4.8.1
  logging: ^1.2.0
  quiver: ^3.2.1
  sentry: ^7.8.0
  supabase: ^1.9.5
  uuid: ^3.0.7
  shared_preferences: "^2.1.1"
  encrypt: ^5.0.1
  cross_file: ^0.3.3+4
  path_provider:
  path:
  audioplayers: ^4.1.0
  record: ^4.4.4

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lint: ^2.1.2
  test: ^1.24.4
