name: studyu_core
version: 4.2.0
description: This package contains StudyU models and common functions for the app and designer packages
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.17.0 # flutter_test
  csv: ^5.0.2
  fhir: ^0.4.7
  json_annotation: ^4.8.1
  logging: ^1.1.1
  quiver: ^3.2.1
  sentry: ^7.5.2
  supabase: ^1.8.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  lint: ^2.0.1
  test: ^1.24.2
