name: studyu_core
description: StudyU Models and common functions for app and designer
version: 3.8.2
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  csv: ^5.0.1
  fhir: ^0.4.7 # 0.6.0
  json_annotation: ^4.8.0
  quiver: ^3.2.1
  supabase: ^0.3.6 # breaking
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  lint: ^2.0.1
  test: ^1.22.2
