name: studyou_core
description: StudYou Models and common functions for app and study designer
version: 0.0.2

publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter_dotenv: 2.1.0
  json_annotation: ^3.1.1
  # Change back to main branch when we do not use back4app or issue is fixed: https://github.com/parse-community/Parse-SDK-Flutter/issues/490
  parse_server_sdk_flutter:
    git:
      url: git://github.com/parse-community/Parse-SDK-Flutter.git
      ref: development
      path: packages/flutter
  quiver: ^2.1.5
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.11
  json_serializable: ^3.5.1
  lint: ^1.5.1
