version: '3'
name: 'studyu_proxy'

networks:
  default:
    name: studyu_network

services:
  proxy:
    container_name: studyu-proxy
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 8082:8082
    # - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
