name: studyu_app
version: 2.4.7
description: An app to facilitate N-of-1 trials
publish_to: none
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  collection: ^1.17.1 # flutter_test sdk
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.5
  # extended_math: # todo remove for null safety support
  # git: https://github.com/nstrelow/extended_math.git
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.1
  flutter_local_notifications: ^15.0.0
  flutter_localizations:
    sdk: flutter
  flutter_timezone: ^1.0.7
  flutter_web_plugins:
    sdk: flutter
  flutter_widget_from_html: ^0.10.2
  # grizzly_distuv: ^1.0.0 # todo remove for null safety support
  intersperse: ^2.0.0
  intl: ^0.18.0 # flutter_localizations
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^4.0.2
  pdf: ^3.10.4
  permission_handler: ^10.4.1
  provider: ^6.0.5
  quiver: ^3.2.1
  rainbow_color: ^2.0.1
  sentry_flutter: ^7.8.0
  sentry_logging: ^7.8.0
  shared_preferences: ^2.2.0
  studyu_core: ^4.3.0-dev.7
  studyu_flutter_common: ^1.6.2-dev.8
  supabase: ^1.9.5
  supabase_flutter: ^1.10.6
  timeline_tile: ^2.0.0
  timezone: ^0.9.2
  universal_html: ^2.2.3
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  wakelock_plus: ^1.0.0+3
  loading_animation_widget: ^1.2.0+4
  record: ^4.4.4
  camera:

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: assets/images/icon.png
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
