name: studyu_app
description: An app to facilitate N-of-1 trials
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

publish_to: 'none'

version: '1.11.3'

environment:
  # todo upgrade to null safety
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  charts_common: ^0.12.0
  charts_flutter: ^0.12.0
  chewie: ^1.4.0
  cupertino_icons: ^1.0.5
  extended_math:
    git:
      url: https://github.com/nstrelow/extended_math.git
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.0
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_timezone: ^1.0.4
  grizzly_distuv: ^1.0.0
  intersperse: ^2.0.0
  intl: ^0.17.0
  material_design_icons_flutter: ^6.0.7096
  package_info_plus: ^3.0.2
  pdf: ^3.8.0
  pimp_my_button: ^1.0.0
  provider: ^6.0.5
  quiver: ^3.2.1
  rainbow_color: ^2.0.1
  shared_preferences: ^2.0.17
  studyu_core: ^3.8.1
  studyu_flutter_common: ^1.3.25
  supabase: ^0.3.6 # breaking
  supabase_flutter: ^0.3.3 # breaking
  timeline_tile: ^2.0.0
  url_launcher: ^6.1.8
  uuid: ^3.0.7
  video_player: ^2.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
     - assets/
     - assets/images/
     - assets/fonts/
