name: StudyU
description: An app to facilitate N-of-1 trials

publish_to: 'none'

version: '1.0.0'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  charts_flutter:
    git:
      url: https://github.com/hpi-studyu/charts.git
      ref: git_export
      path: charts_flutter
  chewie: ^0.12.0
  cupertino_icons: ^1.0.1
  ext_storage: ^1.0.3
  extended_math: ^0.0.29+1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^3.0.2
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^1.0.4
  grizzly_distuv: ^1.0.0
  intersperse: ^1.0.1
  intl: 0.16.1
  json_annotation: ^3.1.1
  material_design_icons_flutter: ^4.0.5655
  parse_server_sdk_flutter:
    git:
      url: git://github.com/parse-community/Parse-SDK-Flutter.git
      ref: development
      path: packages/flutter
  path_provider: ^1.6.24
  pdf: ^1.12.0
  pimp_my_button: ^1.0.0
  provider: ^4.3.2+2
  quiver: ^2.1.5
  rainbow_color: ^0.1.1
  shared_preferences: ^0.5.12
  studyou_core:
    path: ../core
  timeline_tile: ^1.0.0
  url_launcher: ^5.7.10
  video_player: ^1.0.1

dev_dependencies:
  build_runner: ^1.10.6
  build_test: ^1.3.0
  effective_dart: ^1.3.0
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true


flutter:
  generate: true
  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/fonts/
     - envs/
