name: studyu_app
version: 2.6.4
description: Partake in digital N-of-1 trials with the innovative StudyU App
publish_to: none
homepage: https://studyu.health
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  collection: ^1.17.2 # flutter_test
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.6
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.2
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  flutter_timezone: ^1.0.8
  flutter_web_plugins:
    sdk: flutter
  flutter_widget_from_html: ^0.14.6
  intersperse: ^2.0.0
  intl: ^0.18.1
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^4.2.0
  pdf: ^3.10.6
  permission_handler: ^11.0.1
  provider: ^6.1.1
  quiver: ^3.2.1
  rainbow_color: ^2.0.1
  sentry_flutter: ^7.12.0
  sentry_logging: ^7.12.0
  shared_preferences: ^2.2.2
  studyu_core: ^4.3.2
  studyu_flutter_common: ^1.6.4
  supabase: ^1.11.11
  supabase_flutter: ^1.10.25
  timeline_tile: ^2.0.0
  timezone: ^0.9.2
  universal_html: ^2.2.4
  url_launcher: ^6.2.1
  uuid: ^4.1.0 # flutter_test
  wakelock_plus: ^1.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: assets/images/icon.png
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
