name: studyu_notebook_uploader
description: A cli tool to upload html of jupyter notebooks to supabase
version: 1.3.20
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  args: ^2.3.1
  path: ^1.8.2
  studyu_core: ^3.7.14
  supabase: ^0.3.5

dev_dependencies:
  lint: 1.8.2
  shelf_hotreload: ^1.3.0

executables:
  notebook_uploader:
