name: studyu_notebook_uploader
description: A cli tool to upload html of jupyter notebooks to supabase
version: 1.3.24
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  args: ^2.3.2
  path: ^1.8.3
  studyu_core: ^3.8.2
  supabase: ^0.3.6 # breaking

dev_dependencies:
  lint: ^2.0.1
  shelf_hotreload: ^1.4.0

executables:
  notebook_uploader:
