name: studyu_designer_v2
version: 1.3.5
publish_to: none
description: Create digital N-of-1 studies with StudyU

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  archive: ^3.3.7
  async: ^2.11.0
  csv: ^5.0.2
  cupertino_icons: ^1.0.5
  dynamic_color:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_web_plugins:
    sdk: flutter
  go_router: ^8.1.0
  material_color_utilities:
  material_design_icons_flutter: ^7.0.7296
  pointer_interceptor: ^0.9.3+4
  reactive_color_picker: ^1.0.0
  reactive_forms: ^15.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.1.2
  studyu_core: ^4.3.0-dev.3
  studyu_flutter_common: ^1.6.2-dev.4
  supabase: ^1.9.4
  supabase_flutter: ^1.10.4
  url_launcher: ^6.1.11
  uuid: ^3.0.7

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/

