name: studyu_designer_v2
version: 1.6.1
description: Implement digital N-of-1 studies seamlessly with the brand new StudyU Designer
publish_to: none
homepage: https://studyu.health
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  archive: ^3.4.9
  async: ^2.11.0
  csv: ^5.1.1
  cupertino_icons: ^1.0.6
  dynamic_color:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  flutter_web_plugins:
    sdk: flutter
  go_router: ^12.1.1
  material_color_utilities:
  material_design_icons_flutter: ^7.0.7296
  pointer_interceptor: ^0.9.3+7
  reactive_color_picker: ^2.0.0
  reactive_forms: ^16.1.1
  reactive_multi_select_flutter: ^2.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  studyu_core: ^4.3.2
  studyu_flutter_common: ^1.6.4
  supabase: ^1.11.11
  supabase_flutter: ^1.10.25
  url_launcher: ^6.2.1
  uuid: ^4.1.0 # flutter_test

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  patrol_finders: ^1.0.0
  test: ^1.24.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/

