name: studyu_designer
description: StudyU Study designer

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  clipboard: ^0.1.2+8
  csv: ^4.0.3
  cupertino_icons: ^1.0.0
  ext_storage: ^1.0.3
  flutter:
    sdk: flutter
  flutter_form_builder: ^4.0.2
  flutter_iconpicker: ^2.2.2
  flutter_json_widget: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: 0.16.1
  material_design_icons_flutter: ^4.0.5655
  parse_server_sdk_flutter:
    git:
      url: git://github.com/parse-community/Parse-SDK-Flutter.git
      ref: development
      path: packages/flutter
  path_provider: ^1.6.24
  pretty_json: ^1.1.0
  provider: ^4.3.2+2
  studyou_core:
    path: ../core
  universal_html: ^1.2.3
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

dependency_overrides:
  # remove when merged: https://github.com/Realank/flutter_datetime_picker/pull/199
  flutter_datetime_picker:
    git:
      url: https://github.com/espresso3389/flutter_datetime_picker.git
      ref: master

flutter:
  generate: true
  uses-material-design: true

  assets:
    - envs/
