name: studyu_designer
description: StudyU Study designer
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

publish_to: 'none'

version: 1.5.19

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  clipboard: ^0.1.3
  collection: ^1.16.0
  csv: ^5.0.1
  cupertino_icons: ^1.0.5
  email_validator: ^2.1.16
  fl_chart: ^0.46.0 # migrate to ^0.50.5
  flutter:
    sdk: flutter
  flutter_file_dialog: ^2.3.0
  flutter_form_builder: ^7.5.0
  flutter_iconpicker:
    git: https://github.com/dmhuisma/FlutterIconPicker.git
  flutter_localizations:
    sdk: flutter
  form_builder_extra_fields: ^8.3.0
  form_builder_validators: ^8.4.0
  http: ^0.13.4
  intl: 0.17.0
  material_design_icons_flutter: ^5.0.6996
  pretty_json: ^2.0.0
  provider: ^6.0.3
  studyu_core: ^3.7.15
  studyu_flutter_common: ^1.3.22
  supabase: ^0.3.6
  supabase_flutter: ^0.3.3
  universal_html: ^2.0.8
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  webview_flutter: ^3.0.4
  webview_flutter_web: ^0.1.0+4

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
