name: Lint Markdown

on:
  push:
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  lint-markdown:
    name: Markdown-Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Markdown-Lint
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: './**/*.md'
          # check ./.meta/.markdownlintignore
          ignore: './**/CHANGELOG.md ./**/ios/** ./**/android/** ./docs/database/**'
          config: './.meta/.mdlrc'
