name: Lint Markdown

on:
  push:
    paths:
      - '**.md'

jobs:
  lint-markdown:
    name: Markdown-Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Markdown-Lint
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: './**/*.md'
          ignore: './**/CHANGELOG.md ./**/ios/** ./**/android/**'
