name: studyu_flutter_common
description: StudyU common flutter components and functions for app and designer
version: 1.4.0-dev.7
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.18
  studyu_core: ^4.0.0-dev.5
  supabase_flutter: ^1.5.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  generate: true
  assets:
    - packages/studyu_flutter_common/envs/.env
    - packages/studyu_flutter_common/envs/.env.local
    - packages/studyu_flutter_common/envs/.env.selfhost
    - packages/studyu_flutter_common/envs/.env.staging
