name: studyu_flutter_common
description: StudyU common flutter components and functions for app and designer
version: 1.3.26
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.17
  studyu_core: ^3.8.2
  supabase_flutter: ^0.3.3 # breaking
  uuid: ^3.0.7

dev_dependencies:
  lint: ^2.0.1

flutter:
  generate: true
  assets:
    - packages/studyu_flutter_common/envs/.env
    - packages/studyu_flutter_common/envs/.env.local
    - packages/studyu_flutter_common/envs/.env.selfhost
    - packages/studyu_flutter_common/envs/.env.staging
