name: studyu_flutter_common
version: 1.6.2-dev.2
description: StudyU common flutter components and functions for app and designer
homepage: https://hpi.de/lippert/projects/studyu.html
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.1.1
  studyu_core: ^4.3.0-dev.1
  supabase_flutter: ^1.10.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  assets:
    - packages/studyu_flutter_common/envs/.env
    - packages/studyu_flutter_common/envs/.env.local
    - packages/studyu_flutter_common/envs/.env.selfhost
    - packages/studyu_flutter_common/envs/.env.staging
