name: studyu_flutter_common
version: 1.6.4
description: StudyU common flutter components and functions for app and designer
homepage: https://studyu.health
repository: https://github.com/hpi-studyu/studyu

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  studyu_core: ^4.3.2
  supabase_flutter: ^1.10.25
  uuid: ^4.1.0 # flutter_test

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  assets:
    - packages/studyu_flutter_common/envs/.env
    - packages/studyu_flutter_common/envs/.env.dev
    - packages/studyu_flutter_common/envs/.env.local
